connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: C:\Users\ahmed.saidani\Desktop\FMLB\server\fml\libraries\ibm\federated-learning-lib-main\examples\datasets\mnist.npz
  name: MnistPytorchDataHandler
  path: ibmfl.util.data_handlers.mnist_pytorch_data_handler
fusion:
  name: FedAvgFusionHandler
  path: ibmfl.aggregator.fusion.fedavg_fusion_handler
hyperparams:
  global:
    max_timeout: 150
    num_parties: 2
    rounds: 1
    termination_accuracy: 0.9
  local:
    training:
      epochs: 1
      lr: 1
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
